from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Any

import yaml


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_GU_PATH = "data/processed/gt_flow_gu.parquet"


def _resolve_path(path_str: str) -> Path:
    path = Path(path_str)
    if path.is_absolute():
        return path.resolve()
    return (PROJECT_ROOT / path).resolve()


def _load_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        raise ValueError(f"Config must be a YAML mapping: {path}")
    return data


def _load_manifest(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Manifest file not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"Manifest must be a JSON object: {path}")
    return data


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate gu and dong-chunk config YAMLs for the chunked pipeline flow."
    )
    parser.add_argument(
        "--manifest-path",
        required=True,
        help="Path to chunk_manifest.json generated by scripts/35_make_dong_chunks.py",
    )
    parser.add_argument(
        "--base-original-config",
        required=True,
        help="Base full original config YAML path.",
    )
    parser.add_argument(
        "--base-geometry-config",
        required=True,
        help="Base full geometry config YAML path.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory where generated config YAMLs will be written.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=8,
        help="Batch size to write into generated configs. Default: 8",
    )
    return parser


def _set_common_overrides(
    config: dict[str, Any],
    run_id: str,
    batch_size: int,
    enable_rq12: bool,
    enable_rq3: bool,
) -> dict[str, Any]:
    out = copy.deepcopy(config)
    out.setdefault("run", {})
    out["run"]["run_id"] = run_id

    out.setdefault("analysis", {})
    out["analysis"].setdefault("enabled", {})
    out["analysis"]["enabled"]["rq1rq2"] = bool(enable_rq12)
    out["analysis"]["enabled"]["rq3"] = bool(enable_rq3)

    out.setdefault("batching", {})
    out["batching"]["batch_size"] = int(batch_size)
    return out


def _set_gu_path(config: dict[str, Any], gu_path: str) -> None:
    config.setdefault("data", {})
    config["data"].setdefault("datasets", {})
    config["data"]["datasets"].setdefault("gu", {})
    config["data"]["datasets"]["gu"]["path"] = gu_path


def _set_dong_path(config: dict[str, Any], dong_path: str) -> None:
    config.setdefault("data", {})
    config["data"].setdefault("datasets", {})
    config["data"]["datasets"].setdefault("dong", {})
    config["data"]["datasets"]["dong"]["path"] = dong_path


def _write_yaml(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, sort_keys=False, allow_unicode=True)


def _validate_chunks(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    chunks = manifest.get("chunks")
    if not isinstance(chunks, list) or not chunks:
        raise ValueError("Manifest must include a non-empty 'chunks' list.")

    for idx, chunk in enumerate(chunks, start=1):
        if not isinstance(chunk, dict):
            raise ValueError(f"Manifest chunk entry #{idx} is not an object.")
        for key in ("chunk_id", "file_path"):
            value = chunk.get(key)
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"Manifest chunk entry #{idx} missing required key: {key}")
    return chunks


def main() -> None:
    args = _build_parser().parse_args()
    if args.batch_size <= 0:
        raise ValueError("--batch-size must be a positive integer.")

    manifest_path = _resolve_path(args.manifest_path)
    base_original_path = _resolve_path(args.base_original_config)
    base_geometry_path = _resolve_path(args.base_geometry_config)
    output_dir = _resolve_path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest = _load_manifest(manifest_path)
    chunks = _validate_chunks(manifest)
    base_original = _load_yaml(base_original_path)
    base_geometry = _load_yaml(base_geometry_path)

    generated_files: list[str] = []

    gu_jobs = [
        ("gu_original_rq12", base_original, True, False),
        ("gu_geometry_rq12", base_geometry, True, False),
        ("gu_original_rq3", base_original, False, True),
        ("gu_geometry_rq3", base_geometry, False, True),
    ]

    for run_id, base_cfg, enable_rq12, enable_rq3 in gu_jobs:
        cfg = _set_common_overrides(
            config=base_cfg,
            run_id=run_id,
            batch_size=args.batch_size,
            enable_rq12=enable_rq12,
            enable_rq3=enable_rq3,
        )
        _set_gu_path(cfg, DEFAULT_GU_PATH)
        out_path = output_dir / f"{run_id}.yaml"
        _write_yaml(out_path, cfg)
        generated_files.append(str(out_path))

    for chunk in chunks:
        chunk_id = str(chunk["chunk_id"]).strip()
        chunk_num = chunk_id.replace("dong_chunk_", "")
        chunk_path = str(chunk["file_path"])

        for variant_name, base_cfg in (("original", base_original), ("geometry", base_geometry)):
            run_id = f"dong_{variant_name}_chunk_{chunk_num}"
            cfg = _set_common_overrides(
                config=base_cfg,
                run_id=run_id,
                batch_size=args.batch_size,
                enable_rq12=True,
                enable_rq3=False,
            )
            _set_dong_path(cfg, chunk_path)
            out_path = output_dir / f"{run_id}.yaml"
            _write_yaml(out_path, cfg)
            generated_files.append(str(out_path))

    generation_manifest = {
        "manifest_path": str(manifest_path),
        "base_original_config": str(base_original_path),
        "base_geometry_config": str(base_geometry_path),
        "batch_size": int(args.batch_size),
        "number_of_gu_configs_generated": 4,
        "number_of_dong_chunk_configs_generated": int(len(chunks) * 2),
        "output_directory": str(output_dir),
        "generated_files": generated_files,
    }

    generation_manifest_path = output_dir / "config_generation_manifest.json"
    with generation_manifest_path.open("w", encoding="utf-8") as f:
        json.dump(generation_manifest, f, indent=2)
        f.write("\n")

    print(f"Generated {len(generated_files)} config files in {output_dir}")
    print(f"Wrote generation manifest: {generation_manifest_path}")


if __name__ == "__main__":
    main()
